import { Provider } from "@/components/ui/provider";
import Script from "next/script";
import "./globals.css";

export const metadata = {
  title: "GolfiMini",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Script
        id="clarity-script"
        strategy="afterInteractive"
        type="text/javascript"
      >
        {`
          (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
          })(window, document, "clarity", "script", "qt0vudkdqf");
        `}
      </Script>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
